/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examinationmonitoringsystem;

import java.awt.FileDialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rohit Kesarwani
 */
public class RegStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegStudent
     */
    public RegStudent() {
        initComponents();
        loadimage();
    }
    
    private void showerror(String msg)
    {
        JOptionPane.showMessageDialog(this,msg,"error",JOptionPane.ERROR_MESSAGE);
    }
    private void clearblankfield()
    {
        urc.setSelectedIndex(0);
        usession.setSelectedIndex(0);
        ursem.setSelectedIndex(0);
        uroll.setText("");
        uname.setText("");
        umname.setText("");
        ufname.setText("");
        path.setText("");
        loadimage();
    }
    private boolean checkregistrationblankfield()
    {
        if(urc.getSelectedIndex()==0)
        {
            showerror("select course");
            return false;
        }
        else if(usession.getSelectedIndex()==0)
        {
            showerror("select session");
            return false;
        }
        else if(ursem.getSelectedIndex()==0)
        {
            showerror("select semester");
            return false;
        }
        else if(uroll.getText().equals(""))
        {
            showerror("enter roll no");
            return false;
        }
        else if(uname.getText().equals(""))
        {
            showerror("enter student name");
            return false;
        }
        
        else if(umname.getText().equals(""))
        {
            showerror("select mother's name ");
            return false;
        }else if(ufname.getText().equals(""))
        {
            showerror("select father's name");
            return false;
        }
        else if(path.getText().equals("")||path.getText().equals("null")||path.getText().equals("nullnull"))
        {
            showerror("select photo");
            return false;
        }
        else
            return true;
    }
   
    private void loadimage() 
    {
        try
        {
         BufferedImage bf=null;
                  bf=ImageIO.read(new File("./upload/unknown.jpg"));
           Image img=Toolkit.getDefaultToolkit().getImage("./upload/unknown.jpg");
            img=img.getScaledInstance(ph.getWidth(), ph.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ii=new ImageIcon(img);

            ph.setIcon(ii);
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        urc = new javax.swing.JComboBox();
        usession = new javax.swing.JComboBox();
        ursem = new javax.swing.JComboBox();
        ufname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        uroll = new javax.swing.JTextField();
        umname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ph = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Course");

        urc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "B.Tech", "M.Tech", "B.C.A.", "M.C.A.", "P.G.D.C.A.", " " }));
        urc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                urcItemStateChanged(evt);
            }
        });
        urc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urcActionPerformed(evt);
            }
        });

        usession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21", "2021-22", "2022-23", "2023-24", "2024-25", "2025-26" }));
        usession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usessionActionPerformed(evt);
            }
        });

        ursem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));

        ufname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufnameActionPerformed(evt);
            }
        });
        ufname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ufnameKeyTyped(evt);
            }
        });

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unameKeyTyped(evt);
            }
        });

        uroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urollActionPerformed(evt);
            }
        });
        uroll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                urollKeyTyped(evt);
            }
        });

        umname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umnameActionPerformed(evt);
            }
        });
        umname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                umnameKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Semester");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Session");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Un.Roll No");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("First Name");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Mother's Name");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Father's Name");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Photo");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("     NEW USER REGISTRATION");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        path.setEditable(false);

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usession, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(urc, 0, 220, Short.MAX_VALUE)
                                    .addComponent(uroll)
                                    .addComponent(uname)
                                    .addComponent(umname)
                                    .addComponent(ufname)
                                    .addComponent(ursem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(599, 599, 599)
                                .addComponent(ph, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usession, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ursem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uroll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urcActionPerformed

    private void ufnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufnameActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void urollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urollActionPerformed

    private void umnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umnameActionPerformed

    private void usessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usessionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        FileDialog fd=new FileDialog(this,"Select Photo");
        fd.setVisible(true);
        ipath=fd.getDirectory()+fd.getFile();
        path.setText(ipath);
        File f=new File(ipath);
        ftype=ipath.substring(ipath.lastIndexOf(".")+1).toLowerCase();
        //System.out.println(ftype);
        try {
            BufferedImage bf=ImageIO.read(f);
            Image img=Toolkit.getDefaultToolkit().getImage(ipath);
            img=img.getScaledInstance(ph.getWidth(), ph.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ii=new ImageIcon(img);

            ph.setIcon(ii);
        } catch (IOException ex) {}


    }//GEN-LAST:event_jButton2ActionPerformed

    private void urcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_urcItemStateChanged
       ursem.removeAllItems();
ursem.addItem("select");
 if(urc.getSelectedIndex()==1)  
    
{
    ursem.addItem("1");ursem.addItem("2");ursem.addItem("3");ursem.addItem("4");ursem.addItem("5");ursem.addItem("6");ursem.addItem("7");ursem.addItem("8");
    
}
else if(urc.getSelectedIndex()==2)
{
    ursem.addItem("1");ursem.addItem("2");ursem.addItem("3");ursem.addItem("4");
}
else if(urc.getSelectedIndex()==3)
{
    ursem.addItem("1");ursem.addItem("2");ursem.addItem("3");ursem.addItem("4");ursem.addItem("5");ursem.addItem("6");
}
else if(urc.getSelectedIndex()==4)
{
    ursem.addItem("1");ursem.addItem("2");ursem.addItem("3");ursem.addItem("4");
}
else if(urc.getSelectedIndex()==5)
{
    ursem.addItem("1");ursem.addItem("2");
}
    }//GEN-LAST:event_urcItemStateChanged

    private void urollKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urollKeyTyped
char c=evt.getKeyChar();
if (!(c>='0' && c<='9'))
{
    uroll.remove(uroll.getText().length());
}
    }//GEN-LAST:event_urollKeyTyped

    private void unameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyTyped
 char a=evt.getKeyChar();
        if((a>='a'&&a<='z')||(a>='A'&&a<='Z')||a==' ')
        {

        }
        else
        {
            uname.remove(uname.getText().length());
        }
    }//GEN-LAST:event_unameKeyTyped

    private void umnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_umnameKeyTyped

 char a=evt.getKeyChar();
        if((a>='a'&&a<='z')||(a>='A'&&a<='Z')||a==' ')
        {

        }
        else
        {
            umname.remove(umname.getText().length());
        }
    }//GEN-LAST:event_umnameKeyTyped

    private void ufnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ufnameKeyTyped

 char a=evt.getKeyChar();
        if((a>='a'&&a<='z')||(a>='A'&&a<='Z')||a==' ')
        {

        }
        else
        {
            ufname.remove(ufname.getText().length());
        }

    }//GEN-LAST:event_ufnameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        if(checkregistrationblankfield())
        {
            int i=JOptionPane.showConfirmDialog(this,"do u really want to save","confirmation dialog",JOptionPane.YES_NO_OPTION);
           if(i==0)
           {
           Statement s;
            try
            {
                  String  npath="./upload/"+uroll.getText()+"."+ftype;

                s=h.connect();
                s.executeUpdate("insert into s_registration values('"+urc.getSelectedItem().toString()+"','"+usession.getSelectedItem().toString()+"','"+ursem.getSelectedItem().toString()+"','"+uroll.getText().trim()+"','"+uname.getText().toUpperCase().trim()+"','"+umname.getText().trim().toUpperCase()+"','"+ufname.getText().toUpperCase().trim()+"','"+npath+"')");
                h.commit();
              
               h.disconnect();
                    
                    BufferedImage image = null;

                    image= ImageIO.read(new File(path.getText()));

                    ImageIO.write(image,ftype,new File(npath));
                JOptionPane.showMessageDialog(this, "record saved","success registration",JOptionPane.INFORMATION_MESSAGE);
                clearblankfield();
            }catch(Exception e){showerror(e.getMessage());}
           }
        }
         
                    
    }//GEN-LAST:event_jButton1ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField path;
    private javax.swing.JLabel ph;
    private javax.swing.JTextField ufname;
    private javax.swing.JTextField umname;
    private javax.swing.JTextField uname;
    private javax.swing.JComboBox urc;
    private javax.swing.JTextField uroll;
    private javax.swing.JComboBox ursem;
    private javax.swing.JComboBox usession;
    // End of variables declaration//GEN-END:variables
String ipath,ftype;
DatabaseHelper h=new DatabaseHelper();
}
