/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examinationmonitoringsystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rohit
 */
public class RemActiveUsers extends javax.swing.JFrame {

    /**
     * Creates new form RemActiveUsers
     */
    public Socket c;
    public RemActiveUsers() {
        initComponents();
        loadurollno();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ruroll = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("REMOVE ACTIVE USERS");

        ruroll.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ruroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        ruroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rurollActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(ruroll, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(ruroll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadurollno()
    {
      
                  // System.out.println("connection receied");
         //System.out.println("Thread object of particular object is="+socketList.get(ServerMainScreen.socketObjectPosition-1));
      ruroll.removeAllItems();
      ruroll.addItem("Select");
        System.out.print("Loaded");
        Statement s;
        try
        {
            s=h.connect();
           ResultSet r= s.executeQuery("select userid from Active_Login");
          int i=0;
          while(r.next())
          {
              
                ruroll.addItem(r.getString(1));
              
          }
           r.close();
           h.disconnect();
        }catch(Exception e){}

    
    }
    private void loadSocketObject(int p){
        System.out.println("Load Socket Object is called");
            System.out.println("Try block");
            System.out.println("Socket object position ="+p);
            ArrayList<Socket> socketList = ServerMainScreen.list;
            System.out.println("List of socket is="+socketList);
            Socket obj=socketList.get(p-1);
            System.out.println("Socket object got successfully"+obj);
//            ServerMainScreen sms = new ServerMainScreen();
//            ServerMainScreen.ServerThread st = sms.new ServerThread();
//            BufferedReader brc = st.brc;
//            PrintWriter out = st.out;
        try{
            //BufferedReader brc=new BufferedReader(new InputStreamReader(obj.getInputStream()));
            PrintWriter out=new PrintWriter(obj.getOutputStream(), true);
            System.out.println("Connection received");
            out.println("removeActiveUsers");
            out.flush();
        }catch(IOException e){}
    }

    private void rurollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rurollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rurollActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    if(ruroll.getSelectedIndex()!=0)
    {
    int i=JOptionPane.showConfirmDialog(this,"Are you sure want to delete the active user","confirmation deletion",JOptionPane.YES_NO_OPTION);
    
    //System.out.println("value of i="+i);
    if(i==0)
    {
    Statement s = null;
    try
    {
        s=h.connect();
        System.out.println("Load socket object is calling");
        ResultSet rs=s.executeQuery("select socketObjectPosition from Active_Login where userid="+ruroll.getSelectedItem().toString());
            rs.next();
            String p=rs.getString(1);
            System.out.println("Socket object position ="+p);
        
        loadSocketObject(Integer.parseInt(p));
        
        String query="delete from Active_Login where userid='"+ruroll.getSelectedItem().toString()+"'";
        System.out.println(query);
        int success = s.executeUpdate(query);
        System.out.println("value of success="+success);
        h.commit();
        JOptionPane.showMessageDialog(this,"Active user deleted","success deletion",JOptionPane.INFORMATION_MESSAGE);
        h.disconnect();
        
          //new ClientQuestion(c).setVisible(false);
          ruroll.setSelectedIndex(0);
        loadurollno();
    }catch(Exception e){}
    }     
}                                      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RemActiveUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RemActiveUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RemActiveUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RemActiveUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RemActiveUsers().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> ruroll;
    // End of variables declaration//GEN-END:variables
DatabaseHelper h=new DatabaseHelper();

}
