/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examinationmonitoringsystem;

import java.io.File;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rohit Kesarwani
 */
public class RemUser extends javax.swing.JFrame {

    /**
     * Creates new form RemUser
     */
    public RemUser() {
        initComponents();
        loadurollno();
    }
    private void loadurollno()
    {
         
    
      ruroll.removeAllItems();
      ruroll.addItem("select");
        Statement s;
        try
        {
            s=h.connect();
           ResultSet r= s.executeQuery("select  uroll from s_registration");
         
          while(r.next())
          {
              
              
                ruroll.addItem(r.getString(1));
              
          }
           r.close();
           h.disconnect();
        }catch(Exception e){}

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ruroll = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("REMOVE STUDENT");

        ruroll.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ruroll.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", " " }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ruroll, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ruroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

if(ruroll.getSelectedIndex()!=0)
{
    int i=JOptionPane.showConfirmDialog(this,"are you sure want to delete","confirmation deletion",JOptionPane.YES_NO_OPTION);
    if(i==0)
    {
    Statement s;
    try
    {
        s=h.connect();
        ResultSet r=s.executeQuery("select photo from s_registration where uroll="+ruroll.getSelectedItem().toString());
        r.next();
        String p=r.getString(1);
        s.executeUpdate("delete from s_registration where uroll="+ruroll.getSelectedItem().toString());
        h.commit();
        JOptionPane.showMessageDialog(this,"record deleted","success deletion",JOptionPane.INFORMATION_MESSAGE);
        h.disconnect();
        ruroll.setSelectedIndex(0);
        File f=new File(p);
        if(f.exists())
        {
            f.delete();
        }
        loadurollno();
    }catch(Exception e){}
    }     
}
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox ruroll;
    // End of variables declaration//GEN-END:variables
DatabaseHelper h=new DatabaseHelper();
}
